# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#host: 49.248.13.34
#host: 3.0.3.5
#developmentserver: 49.248.13.34
#productionserver: 3.0.3.5

default: &default
  adapter: oracle_enhanced
  database: TLBRNDDB
  host: 49.248.13.34
  username: testora
  password: testora
  port: 1521
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  #pool: 5


development:
  <<: *default
  database: TLBRNDDB

development_web:
  adapter: sqlserver
  host: 209.105.239.188
  username: telebrands_cable
  password: Well@come123
  database: telebrands_cable_operators

development_testora:
  <<: *default
  username: testora
  password: testora
  port: 1521

development_ccview:
  <<: *default
  username: CCVIEW
  password: CCVIEW
  port: 1521

development_cccrm:
  <<: *default
  username: cccrm
  password: cccrm
  port: 1521

development_tuview:
  <<: *default
  username: TUVIEW
  password: TUVIEW
  port: 1521

development_tlbrndu1:
  <<: *default
  username: tlbrndu1
  password: tlbrndu1
  port: 1521

tuview:
  <<: *default
  username: TUVIEW
  password: TUVIEW
  port: 1521

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  #username: surecrmlocal

  # The password associated with the postgres role (username).
  #password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: surecrm_test

# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  adapter: oracle_enhanced
  database: TLBRNDDB
  host: 3.0.3.5
  username: testora
  password: testora
  port: 1521

production_testora:
  adapter: oracle_enhanced
  database: TLBRNDDB
  host: 3.0.3.5
  username: testora
  password: testora
  port: 1521

production_web:
  adapter: "sqlserver"
  host: "209.105.239.188"
  username: "telebrands_cable"
  password: "Well@come123"
  database: "telebrands_cable_operators"

production_ccview:
  adapter: oracle_enhanced
  database: TLBRNDDB
  host: 3.0.3.5
  username: CCVIEW
  password: CCVIEW
  port: 1521

production_cccrm:
  adapter: oracle_enhanced
  database: TLBRNDDB
  host: 3.0.3.5
  username: cccrm
  password: cccrm
  port: 1521

production_tuview:
  adapter: oracle_enhanced
  database: TLBRNDDB
  host: 3.0.3.5
  username: TUVIEW
  password: TUVIEW
  port: 1521

production_tlbrndu1:
  adapter: oracle_enhanced
  database: TLBRNDDB
  host: 3.0.3.5
  username: tlbrndu1
  password: tlbrndu1
  port: 1521

# tuview:
#   adapter: oracle_enhanced
#   database: TLBRNDDB
#   host: 3.0.3.5
#   username: TUVIEW
#   password: TUVIEW
#   port: 1521
