port: 3000
# user: padrino
# group: padrino
pid: tmp/pids/thin.pid
timeout: 300
wait: 30
log: log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 4
threaded: true
no-epoll: true
daemonize: true
socket: tmp/sockets/thin.sock
#chdir: /home/padrino/my-padrino-app
tag: my-padrino-app